// Code generated by dagger. DO NOT EDIT.

package main

import (
	"context"
	"encoding/json"
	"fmt"
	"log/slog"
	"os"
	"sort"

	telemetry "github.com/dagger/otel-go"
	"github.com/vektah/gqlparser/v2/gqlerror"
	"go.opentelemetry.io/otel"
	"go.opentelemetry.io/otel/sdk/resource"
	semconv "go.opentelemetry.io/otel/semconv/v1.40.0"
	"go.opentelemetry.io/otel/trace"

	"dagger/muamba/internal/dagger"

	"github.com/dagger/querybuilder"
)

var dag = dagger.Connect()

func Tracer() trace.Tracer {
	return otel.Tracer("dagger.io/sdk.go")
}

// used for local MarshalJSON implementations
var marshalCtx = context.Background()

// called by main()
func setMarshalContext(ctx context.Context) {
	marshalCtx = ctx
	dagger.SetMarshalContext(ctx)
}

type DaggerObject interface {
	querybuilder.GraphQLMarshaller
	ID(ctx context.Context) (dagger.ID, error)
}

type ExecError = dagger.ExecError

// ptr returns a pointer to the given value.
func ptr[T any](v T) *T {
	return &v
}

// convertSlice converts a slice of one type to a slice of another type using a
// converter function
func convertSlice[I any, O any](in []I, f func(I) O) []O {
	out := make([]O, len(in))
	for i, v := range in {
		out[i] = f(v)
	}
	return out
}

func (r Muamba) MarshalJSON() ([]byte, error) {
	var concrete struct{}
	return json.Marshal(&concrete)
}

func (r *Muamba) UnmarshalJSON(bs []byte) error {
	var concrete struct{}
	return json.Unmarshal(bs, &concrete)
}

func main() {
	ctx := context.Background()

	// Direct slog to the new stderr. This is only for dev time debugging, and
	// runtime errors/warnings.
	slog.SetDefault(slog.New(slog.NewTextHandler(os.Stderr, &slog.HandlerOptions{
		Level: slog.LevelWarn,
	})))

	if err := dispatch(ctx); err != nil {
		os.Exit(2)
	}
}

func convertError(rerr error) *dagger.Error {
	if gqlErr := findSingleGQLError(rerr); gqlErr != nil {
		dagErr := dag.Error(gqlErr.Message)
		if gqlErr.Extensions != nil {
			keys := make([]string, 0, len(gqlErr.Extensions))
			for k := range gqlErr.Extensions {
				keys = append(keys, k)
			}
			sort.Strings(keys)
			for _, k := range keys {
				val, err := json.Marshal(gqlErr.Extensions[k])
				if err != nil {
					fmt.Println("failed to marshal error value:", err)
				}
				dagErr = dagErr.WithValue(k, dagger.JSON(val))
			}
		}
		return dagErr
	}
	return dag.Error(rerr.Error())
}

func findSingleGQLError(rerr error) *gqlerror.Error {
	switch x := rerr.(type) {
	case *gqlerror.Error:
		return x
	case interface{ Unwrap() []error }:
		return nil
	case interface{ Unwrap() error }:
		return findSingleGQLError(x.Unwrap())
	default:
		return nil
	}
}
func dispatch(ctx context.Context) (rerr error) {
	ctx = telemetry.InitEmbedded(ctx, resource.NewWithAttributes(
		semconv.SchemaURL,
		semconv.ServiceNameKey.String("dagger-go-sdk"),
		// TODO version?
	))
	defer telemetry.Close()

	// A lot of the "work" actually happens when we're marshalling the return
	// value, which entails getting object IDs, which happens in MarshalJSON,
	// which has no ctx argument, so we use this lovely global variable.
	setMarshalContext(ctx)

	fnCall := dag.CurrentFunctionCall()
	defer func() {
		if rerr != nil {
			if err := fnCall.ReturnError(ctx, convertError(rerr)); err != nil {
				fmt.Println("failed to return error:", err, "\noriginal error:", rerr)
			}
		}
	}()

	parentName, err := fnCall.ParentName(ctx)
	if err != nil {
		return fmt.Errorf("get parent name: %w", err)
	}
	fnName, err := fnCall.Name(ctx)
	if err != nil {
		return fmt.Errorf("get fn name: %w", err)
	}
	parentJson, err := fnCall.Parent(ctx)
	if err != nil {
		return fmt.Errorf("get fn parent: %w", err)
	}
	fnArgs, err := fnCall.InputArgs(ctx)
	if err != nil {
		return fmt.Errorf("get fn args: %w", err)
	}

	inputArgs := map[string][]byte{}
	for _, fnArg := range fnArgs {
		argName, err := fnArg.Name(ctx)
		if err != nil {
			return fmt.Errorf("get fn arg name: %w", err)
		}
		argValue, err := fnArg.Value(ctx)
		if err != nil {
			return fmt.Errorf("get fn arg value: %w", err)
		}
		inputArgs[argName] = []byte(argValue)
	}

	result, err := invoke(ctx, []byte(parentJson), parentName, fnName, inputArgs)
	if err != nil {
		return err
	}
	resultBytes, err := json.Marshal(result)
	if err != nil {
		return fmt.Errorf("marshal: %w", err)
	}

	if err := fnCall.ReturnValue(ctx, dagger.JSON(resultBytes)); err != nil {
		return fmt.Errorf("store return value: %w", err)
	}
	return nil
}
func invoke(ctx context.Context, parentJSON []byte, parentName string, fnName string, inputArgs map[string][]byte) (_ any, err error) {
	if parentName != "Muamba" {
		return nil, fmt.Errorf("unknown object %s", parentName)
	}
	var parent Muamba
	if err := json.Unmarshal(parentJSON, &parent); err != nil {
		return nil, fmt.Errorf("failed to unmarshal parent object: %w", err)
	}
	source, err := decodeInput[*dagger.Directory](inputArgs, "source")
	if err != nil {
		return nil, err
	}

	switch fnName {
	case "Build":
		trustDomain, err := decodeInput[string](inputArgs, "trustDomain")
		if err != nil {
			return nil, err
		}
		return parent.Build(ctx, source, trustDomain)
	case "Check":
		minimum, err := decodeInput[string](inputArgs, "minimumCoverage")
		if err != nil {
			return nil, err
		}
		trustDomain, err := decodeInput[string](inputArgs, "trustDomain")
		if err != nil {
			return nil, err
		}
		runNonce, err := decodeInput[string](inputArgs, "runNonce")
		if err != nil {
			return nil, err
		}
		return parent.Check(ctx, source, minimum, trustDomain, runNonce)
	case "Coverage":
		minimum, err := decodeInput[string](inputArgs, "minimumCoverage")
		if err != nil {
			return nil, err
		}
		trustDomain, err := decodeInput[string](inputArgs, "trustDomain")
		if err != nil {
			return nil, err
		}
		return parent.Coverage(ctx, source, minimum, trustDomain)
	case "CoverageReport":
		trustDomain, err := decodeInput[string](inputArgs, "trustDomain")
		if err != nil {
			return nil, err
		}
		runNonce, err := decodeInput[string](inputArgs, "runNonce")
		if err != nil {
			return nil, err
		}
		return parent.CoverageReport(ctx, source, trustDomain, runNonce)
	case "Examples":
		trustDomain, err := decodeInput[string](inputArgs, "trustDomain")
		if err != nil {
			return nil, err
		}
		return parent.Examples(ctx, source, trustDomain)
	case "Format":
		trustDomain, err := decodeInput[string](inputArgs, "trustDomain")
		if err != nil {
			return nil, err
		}
		return parent.Format(ctx, source, trustDomain)
	case "Lint":
		trustDomain, err := decodeInput[string](inputArgs, "trustDomain")
		if err != nil {
			return nil, err
		}
		return parent.Lint(ctx, source, trustDomain)
	case "Module":
		trustDomain, err := decodeInput[string](inputArgs, "trustDomain")
		if err != nil {
			return nil, err
		}
		return parent.Module(ctx, source, trustDomain)
	case "Race":
		trustDomain, err := decodeInput[string](inputArgs, "trustDomain")
		if err != nil {
			return nil, err
		}
		return parent.Race(ctx, source, trustDomain)
	case "ReleaseSnapshot":
		trustDomain, err := decodeInput[string](inputArgs, "trustDomain")
		if err != nil {
			return nil, err
		}
		return parent.ReleaseSnapshot(ctx, source, trustDomain)
	case "ReleaseTest":
		trustDomain, err := decodeInput[string](inputArgs, "trustDomain")
		if err != nil {
			return nil, err
		}
		runNonce, err := decodeInput[string](inputArgs, "runNonce")
		if err != nil {
			return nil, err
		}
		return parent.ReleaseTest(ctx, source, trustDomain, runNonce)
	case "Vet":
		trustDomain, err := decodeInput[string](inputArgs, "trustDomain")
		if err != nil {
			return nil, err
		}
		return parent.Vet(ctx, source, trustDomain)
	case "PublishRelease":
		githubToken, err := decodeInput[*dagger.Secret](inputArgs, "githubToken")
		if err != nil {
			return nil, err
		}
		oidcToken, err := decodeInput[*dagger.Secret](inputArgs, "oidcToken")
		if err != nil {
			return nil, err
		}
		oidcURL, err := decodeInput[*dagger.Secret](inputArgs, "oidcURL")
		if err != nil {
			return nil, err
		}
		tag, err := decodeInput[string](inputArgs, "tag")
		if err != nil {
			return nil, err
		}
		commit, err := decodeInput[string](inputArgs, "commit")
		if err != nil {
			return nil, err
		}
		repository, err := decodeInput[string](inputArgs, "repository")
		if err != nil {
			return nil, err
		}
		trustDomain, err := decodeInput[string](inputArgs, "trustDomain")
		if err != nil {
			return nil, err
		}
		runNonce, err := decodeInput[string](inputArgs, "runNonce")
		if err != nil {
			return nil, err
		}
		return parent.PublishRelease(ctx, source, githubToken, oidcToken, oidcURL, tag, commit, repository, trustDomain, runNonce)
	default:
		return nil, fmt.Errorf("unknown function %s", fnName)
	}
}

func decodeInput[T any](inputArgs map[string][]byte, name string) (T, error) {
	var value T
	if inputArgs[name] == nil {
		return value, nil
	}
	if err := json.Unmarshal(inputArgs[name], &value); err != nil {
		return value, fmt.Errorf("failed to unmarshal input arg %s: %w", name, err)
	}
	return value, nil
}
