// Code generated by muamba. DO NOT EDIT.

package assets

import (
	"embed"
	"fmt"
	"io/fs"
)

//go:embed vendor/bootstrap/5.3.8/LICENSE vendor/bootstrap/5.3.8/bootstrap.bundle.min.js vendor/bootstrap/5.3.8/bootstrap.min.css
var muambaFiles embed.FS

const (
	muambaDownloadBootstrapBundleJs = "bundle-js"
	muambaDownloadBootstrapCoreCss  = "core-css"
	muambaDownloadBootstrapLicense  = "license"
	muambaResourceBootstrap         = "bootstrap"
)

type MuambaResource struct {
	Name      string
	Version   string
	Downloads []MuambaDownload
}

type MuambaDownload struct {
	Name      string
	URL       string
	Path      string
	Integrity string
}

var muambaResources = []MuambaResource{
	{Name: "bootstrap", Version: "5.3.8", Downloads: []MuambaDownload{
		{Name: "bundle-js", URL: "https://unpkg.com/bootstrap@5.3.8/dist/js/bootstrap.bundle.min.js", Path: "assets/vendor/bootstrap/5.3.8/bootstrap.bundle.min.js", Integrity: "sha384-FKyoEForCGlyvwx9Hj09JcYn3nv7wiPVlz7YYwJrWVcXK/BmnVDxM+D2scQbITxI"},
		{Name: "core-css", URL: "https://unpkg.com/bootstrap@5.3.8/dist/css/bootstrap.min.css", Path: "assets/vendor/bootstrap/5.3.8/bootstrap.min.css", Integrity: "sha384-sRIl4kxILFvY47J16cr9ZwB07vP4J8+LH7qKQnuqkuIAvNWLzeN8tE5YBujZqJLB"},
		{Name: "license", URL: "https://unpkg.com/bootstrap@5.3.8/LICENSE", Path: "assets/vendor/bootstrap/5.3.8/LICENSE", Integrity: "sha384-WyeULmOarnkxIWJQ6Byifrdakj+J3Z1ONoIjyqqdmUvfwML66D4izPruHb7zDZbG"},
	}},
}

var muambaEmbeddedPaths = map[string]string{
	"bootstrap\x00bundle-js": "vendor/bootstrap/5.3.8/bootstrap.bundle.min.js",
	"bootstrap\x00core-css":  "vendor/bootstrap/5.3.8/bootstrap.min.css",
	"bootstrap\x00license":   "vendor/bootstrap/5.3.8/LICENSE",
}

func MuambaResources() []MuambaResource {
	result := make([]MuambaResource, len(muambaResources))
	copy(result, muambaResources)
	for index := range result {
		result[index].Downloads = append([]MuambaDownload(nil), result[index].Downloads...)
	}
	return result
}

func MuambaResourceByName(name string) (MuambaResource, bool) {
	for _, resource := range MuambaResources() {
		if resource.Name == name {
			return resource, true
		}
	}
	return MuambaResource{}, false
}

func MuambaOpen(resource, download string) (fs.File, error) {
	path, ok := muambaEmbeddedPaths[resource+"\x00"+download]
	if !ok {
		return nil, fmt.Errorf("unknown Muamba download %s/%s", resource, download)
	}
	return muambaFiles.Open(path)
}
